
pc_colnames = [
               'NPI', 'PAC ID', 'Professional Enrollment ID', 'Last Name',
               'First Name', 'Middle Name', 'Suffix', 'Gender', 'Credential',
               'Medical school name', 'Graduation year', 'Primary specialty',
               'Secondary specialty 1', 'Secondary specialty 2',
               'Secondary specialty 3', 'Secondary specialty 4',
               'All secondary specialties', 'Organization legal name',
               'Group Practice PAC ID', 'Number of Group Practice members',
               'Line 1 Street Address', 'Line 2 Street Address',
               'Marker of address line 2 suppression', 'City', 'State',
               'Zip Code',
               'Hospital affiliation CCN 1', 'Hospital affiliation LBN 1',
               'Hospital affiliation CCN 2',  'Hospital affiliation LBN 2',
               'Hospital affiliation CCN 3',  'Hospital affiliation LBN 3',
               'Hospital affiliation CCN 4',  'Hospital affiliation LBN 4',
               'Hospital affiliation CCN 5',  'Hospital affiliation LBN 5',
               'Professional accepts Medicare Assignment',
               'Reported Quality Measures', 'Used electronic health records',
               'Committed to heart health through the Million Hearts'
               ' initiative'
               ]

pc_col_dict = {'NPI': 'NPI',
               'Ind_PAC_ID': 'PAC ID',
               'Ind_enrl_ID': 'Professional Enrollment ID',
               'lst_nm': 'Last Name',
               'frst_nm': 'First Name',
               'mid_nm': 'Middle Name',
               'suff': 'Suffix',
               'gndr': 'Gender',
               'Cred': 'Credential',
               'Med_sch': 'Medical school name',
               'Grd_yr': 'Graduation year',
               'Pri_spec': 'Primary specialty',
               'Sec_spec_1': 'Secondary specialty 1',
               'Sec_spec_2': 'Secondary specialty 2',
               'Sec_spec_3': 'Secondary specialty 3',
               'Sec_spec_4': 'Secondary specialty 4',
               'Sec_spec_all': 'All secondary specialties',
               'Org_lgl_nm': 'Organization legal name',
               'Org_PAC_ID': 'Group Practice PAC ID',
               'num_org_mem': 'Number of Group Practice members',
               'adr_ln_1': 'Line 1 Street Address',
               'adr_ln_2': 'Line 2 Street Address',
               'ln_2_sprs': 'Marker of address line 2 suppression',
               'cty': 'City',
               'st': 'State',
               'zip': 'Zip Code',
               'hosp_afl_1': 'Hospital affiliation CCN 1',
               'hosp_afl_lbn_1': 'Hospital affiliation LBN 1',
               'hosp_afl_2': 'Hospital affiliation CCN 2',
               'hosp_afl_lbn_2': 'Hospital affiliation LBN 2',
               'hosp_afl_3': 'Hospital affiliation CCN 3',
               'hosp_afl_lbn_3': 'Hospital affiliation LBN 3',
               'hosp_afl_4': 'Hospital affiliation CCN 4',
               'hosp_afl_lbn_4': 'Hospital affiliation LBN 4',
               'hosp_afl_5': 'Hospital affiliation CCN 5',
               'hosp_afl_lbn_5': 'Hospital affiliation LBN 5',
               'assgn': 'Professional accepts Medicare Assignment'}

pc_col_dict_reverse = {x: y for y, x in pc_col_dict.items()}


{'National_Downloadable_File-11.csv': '2015-04-03',
 'National_Downloadable_File-7.csv': '2015-11-05',
 'National_Downloadable_File-6.csv': '2016-03-31',
 'National_Downloadable_File-10.csv': '2015-02-10',
 'National_Downloadable_File-12.csv': '2014-06-19',
 'National_Downloadable_File-13.csv': '2014-09-24',
 'National_Downloadable_File-8.csv': '2015-10-01',
 'National_Downloadable_File-9.csv': '2015-07-06',
 'National_Downloadable_File_2018_12.csv': '2018-12-10',
 'National_Downloadable_File_2018_10.csv': '2018-10-03',
 'Refresh_Data_Archive_March_2014': '2014-03-12'
 }

['/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_April_2015_1',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_10_2017',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_April_2016_1',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_07_2017',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_June_2014',
 '/work/akilby/npi/raw_medicare/physician_compare/PHC_Refresh_Data_Archive_07_2018',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_November_2015_1',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_December_2014',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_04_2017',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_September_2014',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_12_2016',
 '/work/akilby/npi/raw_medicare/physician_compare/PHC_Refresh_Data_Archive_04_2018',
 '/work/akilby/npi/raw_medicare/physician_compare/PHC_Refresh_Data_Archive_12_2017',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_10_2016',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_07_2016',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_July_2015_1',
 '/work/akilby/npi/raw_medicare/physician_compare/PHC_Refresh_Data_Archive_10_2018',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_October_2015_1',
 '/work/akilby/npi/raw_medicare/physician_compare/PHC_Refresh_Data_Archive_12_2018',
 '/work/akilby/npi/raw_medicare/physician_compare/Refresh_Data_Archive_March_2014']
